# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import accesspolicyentity
    from ._models_py3 import accesspolicyentitycollection
    from ._models_py3 import accountencryption
    from ._models_py3 import audioencoderaac
    from ._models_py3 import audioencoderbase
    from ._models_py3 import authenticationbase
    from ._models_py3 import certificatesource
    from ._models_py3 import checknameavailabilityrequest
    from ._models_py3 import checknameavailabilityresponse
    from ._models_py3 import credentialsbase
    from ._models_py3 import ecctokenkey
    from ._models_py3 import edgemoduleentity
    from ._models_py3 import edgemoduleentitycollection
    from ._models_py3 import edgemoduleprovisioningtoken
    from ._models_py3 import encodercustompreset
    from ._models_py3 import encoderpresetbase
    from ._models_py3 import encoderprocessor
    from ._models_py3 import encodersystempreset
    from ._models_py3 import endpoint
    from ._models_py3 import endpointbase
    from ._models_py3 import erroradditionalinfo
    from ._models_py3 import errordetail
    from ._models_py3 import errorresponse
    from ._models_py3 import grouplevelaccesscontrol
    from ._models_py3 import iothub
    from ._models_py3 import jwtauthentication
    from ._models_py3 import keyvaultproperties
    from ._models_py3 import listprovisioningtokeninput
    from ._models_py3 import livepipeline
    from ._models_py3 import livepipelinecollection
    from ._models_py3 import livepipelineoperationstatus
    from ._models_py3 import livepipelineupdate
    from ._models_py3 import logspecification
    from ._models_py3 import metricdimension
    from ._models_py3 import metricspecification
    from ._models_py3 import networkaccesscontrol
    from ._models_py3 import nodebase
    from ._models_py3 import nodeinput
    from ._models_py3 import operation
    from ._models_py3 import operationcollection
    from ._models_py3 import operationdisplay
    from ._models_py3 import parameterdeclaration
    from ._models_py3 import parameterdefinition
    from ._models_py3 import pemcertificatelist
    from ._models_py3 import pipelinejob
    from ._models_py3 import pipelinejobcollection
    from ._models_py3 import pipelinejoberror
    from ._models_py3 import pipelinejoboperationstatus
    from ._models_py3 import pipelinejobupdate
    from ._models_py3 import pipelinetopology
    from ._models_py3 import pipelinetopologycollection
    from ._models_py3 import pipelinetopologyupdate
    from ._models_py3 import privateendpoint
    from ._models_py3 import privateendpointconnection
    from ._models_py3 import privateendpointconnectionlistresult
    from ._models_py3 import privatelinkresource
    from ._models_py3 import privatelinkresourcelistresult
    from ._models_py3 import privatelinkserviceconnectionstate
    from ._models_py3 import processornodebase
    from ._models_py3 import properties
    from ._models_py3 import proxyresource
    from ._models_py3 import resource
    from ._models_py3 import resourceidentity
    from ._models_py3 import rsatokenkey
    from ._models_py3 import rtspsource
    from ._models_py3 import secureiotdeviceremotetunnel
    from ._models_py3 import servicespecification
    from ._models_py3 import sinknodebase
    from ._models_py3 import sku
    from ._models_py3 import sourcenodebase
    from ._models_py3 import storageaccount
    from ._models_py3 import systemdata
    from ._models_py3 import timesequencebase
    from ._models_py3 import tlsendpoint
    from ._models_py3 import tlsvalidationoptions
    from ._models_py3 import tokenclaim
    from ._models_py3 import tokenkey
    from ._models_py3 import trackedresource
    from ._models_py3 import tunnelbase
    from ._models_py3 import unsecuredendpoint
    from ._models_py3 import userassignedmanagedidentity
    from ._models_py3 import usernamepasswordcredentials
    from ._models_py3 import videoanalyzer
    from ._models_py3 import videoanalyzercollection
    from ._models_py3 import videoanalyzeridentity
    from ._models_py3 import videoanalyzeroperationstatus
    from ._models_py3 import videoanalyzerprivateendpointconnectionoperationstatus
    from ._models_py3 import videoanalyzerupdate
    from ._models_py3 import videoarchival
    from ._models_py3 import videocontenttoken
    from ._models_py3 import videocontenturls
    from ._models_py3 import videocreationproperties
    from ._models_py3 import videoencoderbase
    from ._models_py3 import videoencoderh264
    from ._models_py3 import videoentity
    from ._models_py3 import videoentitycollection
    from ._models_py3 import videoflags
    from ._models_py3 import videomediainfo
    from ._models_py3 import videopreviewimageurls
    from ._models_py3 import videopublishingoptions
    from ._models_py3 import videoscale
    from ._models_py3 import videosequenceabsolutetimemarkers
    from ._models_py3 import videosink
    from ._models_py3 import videosource
except (SyntaxError, ImportError):
    from ._models import accesspolicyentity  # type: ignore
    from ._models import accesspolicyentitycollection  # type: ignore
    from ._models import accountencryption  # type: ignore
    from ._models import audioencoderaac  # type: ignore
    from ._models import audioencoderbase  # type: ignore
    from ._models import authenticationbase  # type: ignore
    from ._models import certificatesource  # type: ignore
    from ._models import checknameavailabilityrequest  # type: ignore
    from ._models import checknameavailabilityresponse  # type: ignore
    from ._models import credentialsbase  # type: ignore
    from ._models import ecctokenkey  # type: ignore
    from ._models import edgemoduleentity  # type: ignore
    from ._models import edgemoduleentitycollection  # type: ignore
    from ._models import edgemoduleprovisioningtoken  # type: ignore
    from ._models import encodercustompreset  # type: ignore
    from ._models import encoderpresetbase  # type: ignore
    from ._models import encoderprocessor  # type: ignore
    from ._models import encodersystempreset  # type: ignore
    from ._models import endpoint  # type: ignore
    from ._models import endpointbase  # type: ignore
    from ._models import erroradditionalinfo  # type: ignore
    from ._models import errordetail  # type: ignore
    from ._models import errorresponse  # type: ignore
    from ._models import grouplevelaccesscontrol  # type: ignore
    from ._models import iothub  # type: ignore
    from ._models import jwtauthentication  # type: ignore
    from ._models import keyvaultproperties  # type: ignore
    from ._models import listprovisioningtokeninput  # type: ignore
    from ._models import livepipeline  # type: ignore
    from ._models import livepipelinecollection  # type: ignore
    from ._models import livepipelineoperationstatus  # type: ignore
    from ._models import livepipelineupdate  # type: ignore
    from ._models import logspecification  # type: ignore
    from ._models import metricdimension  # type: ignore
    from ._models import metricspecification  # type: ignore
    from ._models import networkaccesscontrol  # type: ignore
    from ._models import nodebase  # type: ignore
    from ._models import nodeinput  # type: ignore
    from ._models import operation  # type: ignore
    from ._models import operationcollection  # type: ignore
    from ._models import operationdisplay  # type: ignore
    from ._models import parameterdeclaration  # type: ignore
    from ._models import parameterdefinition  # type: ignore
    from ._models import pemcertificatelist  # type: ignore
    from ._models import pipelinejob  # type: ignore
    from ._models import pipelinejobcollection  # type: ignore
    from ._models import pipelinejoberror  # type: ignore
    from ._models import pipelinejoboperationstatus  # type: ignore
    from ._models import pipelinejobupdate  # type: ignore
    from ._models import pipelinetopology  # type: ignore
    from ._models import pipelinetopologycollection  # type: ignore
    from ._models import pipelinetopologyupdate  # type: ignore
    from ._models import privateendpoint  # type: ignore
    from ._models import privateendpointconnection  # type: ignore
    from ._models import privateendpointconnectionlistresult  # type: ignore
    from ._models import privatelinkresource  # type: ignore
    from ._models import privatelinkresourcelistresult  # type: ignore
    from ._models import privatelinkserviceconnectionstate  # type: ignore
    from ._models import processornodebase  # type: ignore
    from ._models import properties  # type: ignore
    from ._models import proxyresource  # type: ignore
    from ._models import resource  # type: ignore
    from ._models import resourceidentity  # type: ignore
    from ._models import rsatokenkey  # type: ignore
    from ._models import rtspsource  # type: ignore
    from ._models import secureiotdeviceremotetunnel  # type: ignore
    from ._models import servicespecification  # type: ignore
    from ._models import sinknodebase  # type: ignore
    from ._models import sku  # type: ignore
    from ._models import sourcenodebase  # type: ignore
    from ._models import storageaccount  # type: ignore
    from ._models import systemdata  # type: ignore
    from ._models import timesequencebase  # type: ignore
    from ._models import tlsendpoint  # type: ignore
    from ._models import tlsvalidationoptions  # type: ignore
    from ._models import tokenclaim  # type: ignore
    from ._models import tokenkey  # type: ignore
    from ._models import trackedresource  # type: ignore
    from ._models import tunnelbase  # type: ignore
    from ._models import unsecuredendpoint  # type: ignore
    from ._models import userassignedmanagedidentity  # type: ignore
    from ._models import usernamepasswordcredentials  # type: ignore
    from ._models import videoanalyzer  # type: ignore
    from ._models import videoanalyzercollection  # type: ignore
    from ._models import videoanalyzeridentity  # type: ignore
    from ._models import videoanalyzeroperationstatus  # type: ignore
    from ._models import videoanalyzerprivateendpointconnectionoperationstatus  # type: ignore
    from ._models import videoanalyzerupdate  # type: ignore
    from ._models import videoarchival  # type: ignore
    from ._models import videocontenttoken  # type: ignore
    from ._models import videocontenturls  # type: ignore
    from ._models import videocreationproperties  # type: ignore
    from ._models import videoencoderbase  # type: ignore
    from ._models import videoencoderh264  # type: ignore
    from ._models import videoentity  # type: ignore
    from ._models import videoentitycollection  # type: ignore
    from ._models import videoflags  # type: ignore
    from ._models import videomediainfo  # type: ignore
    from ._models import videopreviewimageurls  # type: ignore
    from ._models import videopublishingoptions  # type: ignore
    from ._models import videoscale  # type: ignore
    from ._models import videosequenceabsolutetimemarkers  # type: ignore
    from ._models import videosink  # type: ignore
    from ._models import videosource  # type: ignore

from ._video_analyzer_enums import (
    Accesspolicyeccalgo,
    Accesspolicyrole,
    Accesspolicyrsaalgo,
    Accountencryptionkeytype,
    Actiontype,
    Checknameavailabilityreason,
    Createdbytype,
    Encodersystempresettype,
    Kind,
    Livepipelinestate,
    Metricaggregationtype,
    Metricunit,
    Parametertype,
    Pipelinejobstate,
    Privateendpointconnectionprovisioningstate,
    Privateendpointserviceconnectionstatus,
    Provisioningstate,
    Publicnetworkaccess,
    Rtsptransport,
    Skuname,
    Skutier,
    Videoanalyzerendpointtype,
    Videoscalemode,
    Videotype,
)

__all__ = [
    'accesspolicyentity',
    'accesspolicyentitycollection',
    'accountencryption',
    'audioencoderaac',
    'audioencoderbase',
    'authenticationbase',
    'certificatesource',
    'checknameavailabilityrequest',
    'checknameavailabilityresponse',
    'credentialsbase',
    'ecctokenkey',
    'edgemoduleentity',
    'edgemoduleentitycollection',
    'edgemoduleprovisioningtoken',
    'encodercustompreset',
    'encoderpresetbase',
    'encoderprocessor',
    'encodersystempreset',
    'endpoint',
    'endpointbase',
    'erroradditionalinfo',
    'errordetail',
    'errorresponse',
    'grouplevelaccesscontrol',
    'iothub',
    'jwtauthentication',
    'keyvaultproperties',
    'listprovisioningtokeninput',
    'livepipeline',
    'livepipelinecollection',
    'livepipelineoperationstatus',
    'livepipelineupdate',
    'logspecification',
    'metricdimension',
    'metricspecification',
    'networkaccesscontrol',
    'nodebase',
    'nodeinput',
    'operation',
    'operationcollection',
    'operationdisplay',
    'parameterdeclaration',
    'parameterdefinition',
    'pemcertificatelist',
    'pipelinejob',
    'pipelinejobcollection',
    'pipelinejoberror',
    'pipelinejoboperationstatus',
    'pipelinejobupdate',
    'pipelinetopology',
    'pipelinetopologycollection',
    'pipelinetopologyupdate',
    'privateendpoint',
    'privateendpointconnection',
    'privateendpointconnectionlistresult',
    'privatelinkresource',
    'privatelinkresourcelistresult',
    'privatelinkserviceconnectionstate',
    'processornodebase',
    'properties',
    'proxyresource',
    'resource',
    'resourceidentity',
    'rsatokenkey',
    'rtspsource',
    'secureiotdeviceremotetunnel',
    'servicespecification',
    'sinknodebase',
    'sku',
    'sourcenodebase',
    'storageaccount',
    'systemdata',
    'timesequencebase',
    'tlsendpoint',
    'tlsvalidationoptions',
    'tokenclaim',
    'tokenkey',
    'trackedresource',
    'tunnelbase',
    'unsecuredendpoint',
    'userassignedmanagedidentity',
    'usernamepasswordcredentials',
    'videoanalyzer',
    'videoanalyzercollection',
    'videoanalyzeridentity',
    'videoanalyzeroperationstatus',
    'videoanalyzerprivateendpointconnectionoperationstatus',
    'videoanalyzerupdate',
    'videoarchival',
    'videocontenttoken',
    'videocontenturls',
    'videocreationproperties',
    'videoencoderbase',
    'videoencoderh264',
    'videoentity',
    'videoentitycollection',
    'videoflags',
    'videomediainfo',
    'videopreviewimageurls',
    'videopublishingoptions',
    'videoscale',
    'videosequenceabsolutetimemarkers',
    'videosink',
    'videosource',
    'Accesspolicyeccalgo',
    'Accesspolicyrole',
    'Accesspolicyrsaalgo',
    'Accountencryptionkeytype',
    'Actiontype',
    'Checknameavailabilityreason',
    'Createdbytype',
    'Encodersystempresettype',
    'Kind',
    'Livepipelinestate',
    'Metricaggregationtype',
    'Metricunit',
    'Parametertype',
    'Pipelinejobstate',
    'Privateendpointconnectionprovisioningstate',
    'Privateendpointserviceconnectionstatus',
    'Provisioningstate',
    'Publicnetworkaccess',
    'Rtsptransport',
    'Skuname',
    'Skutier',
    'Videoanalyzerendpointtype',
    'Videoscalemode',
    'Videotype',
]
