# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._edgemodules_operations import edgemodulesOperations
from ._pipelinetopologies_operations import pipelinetopologiesOperations
from ._livepipelines_operations import livepipelinesOperations
from ._pipelinejobs_operations import pipelinejobsOperations
from ._livepipelineoperationstatuses_operations import livepipelineoperationstatusesOperations
from ._pipelinejoboperationstatuses_operations import pipelinejoboperationstatusesOperations
from ._operations import operationsOperations
from ._videoanalyzers_operations import videoanalyzersOperations
from ._privatelinkresources_operations import privatelinkresourcesOperations
from ._privateendpointconnections_operations import privateendpointconnectionsOperations
from ._operationstatuses_operations import operationstatusesOperations
from ._operationresults_operations import operationresultsOperations
from ._videoanalyzeroperationstatuses_operations import videoanalyzeroperationstatusesOperations
from ._videoanalyzeroperationresults_operations import videoanalyzeroperationresultsOperations
from ._locations_operations import locationsOperations
from ._videos_operations import videosOperations
from ._accesspolicies_operations import accesspoliciesOperations

__all__ = [
    'edgemodulesOperations',
    'pipelinetopologiesOperations',
    'livepipelinesOperations',
    'pipelinejobsOperations',
    'livepipelineoperationstatusesOperations',
    'pipelinejoboperationstatusesOperations',
    'operationsOperations',
    'videoanalyzersOperations',
    'privatelinkresourcesOperations',
    'privateendpointconnectionsOperations',
    'operationstatusesOperations',
    'operationresultsOperations',
    'videoanalyzeroperationstatusesOperations',
    'videoanalyzeroperationresultsOperations',
    'locationsOperations',
    'videosOperations',
    'accesspoliciesOperations',
]
